### ISSUE TITLE
The Time it takes to run basicParam example on computer 11 is longer than the time it takes computer 5

### ISSUE THREAD

**Issue by trakevital** [M-R-VulcaN/crazyflie-link-cpp#6]
Computer 5: 

![image](https://user-images.githubusercontent.com/32649570/119654913-9d7fb780-be31-11eb-80d5-f4a4a4b690d9.png)

**Comment by Steven-Sorokin** [comment]
computer 11:

![image](https://user-images.githubusercontent.com/67019760/119655011-bf793a00-be31-11eb-9f5e-74a887feb869.png)

**Comment by trakevital** [comment]
**Turns out the splitter reduces the speed of the crazyflie connection by a factor of 2**
